# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rom_id', models.CharField(max_length=30, unique=True)),
                ('intercept', models.CharField(max_length=20)),
                ('p', models.CharField(max_length=20)),
                ('p_p', models.CharField(max_length=20)),
                ('t', models.CharField(max_length=20)),
                ('t_p', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=20)),
                ('b', models.CharField(max_length=20)),
                ('min_range', models.IntegerField()),
                ('max_range', models.IntegerField()),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
                ('level', models.CharField(max_length=30)),
                ('g', models.CharField(max_length=20)),
                ('temperature', models.IntegerField()),
            ],
        ),
    ]
