# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181115_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rom_id', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('pressure', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('s_volt', models.IntegerField()),
                ('s_press', models.IntegerField()),
                ('s_temp', models.IntegerField()),
                ('s_data', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='SoftTest',
        ),
    ]
