# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181129_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_data',
            name='s_volt',
            field=models.FloatField(),
        ),
    ]
